development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  password: <%= ENV['REDIS_PASSWORD'] || '' %>
test:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  password: <%= ENV['REDIS_PASSWORD'] || '' %>  
production:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  password: <%= ENV['REDIS_PASSWORD'] || '' %>  
