source 'https://rubygems.org'

ruby '3.3.5'

# Rails Dependencies
# =====================================================
gem "rails", "~> 7.0.8"
gem 'bundler'
gem 'rake', '~> 13.0.1'
gem 'puma', '~> 6.4.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'turbolinks', '~> 5'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
gem 'sdoc', '~> 2.6.1', group: :doc

# removed from standard rails these gems need to be installed separately in the future
gem 'mutex_m' # no longer be part of the default gems starting from Ruby 3.4.0
gem 'base64' # no longer be part of the default gems starting from Ruby 3.4.0
gem 'fiddle' # no longer be part of the default gems starting from Ruby 3.4.0

# Frontend Dependencies
# =====================================================
gem "sassc-rails", "~> 2.1"
gem "sprockets-rails"
# gem "importmap-rails"
# gem "turbo-rails"
# gem "stimulus-rails"
gem "bootstrap", "~> 5.1"

gem 'bootsnap', '>= 1.4.2', require: false

gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'

gem 'mime-types'

# OAI-PMH
# =====================================================
gem 'blacklight_oai_provider', github: 'projectblacklight/blacklight_oai_provider', ref: '428da77'

# Automatic Import
# =====================================================
gem 'whenever', require: false

# Bulkrax Import
# =====================================================
# Switch the comments on these two lines to work on Bulkrax locally
# gem 'bulkrax', git: 'https://github.com/samvera-labs/bulkrax.git' , ref: 'b689afa'
# Rails 7 support - pinned to commit (check if released version available)
gem 'bulkrax', github: 'samvera/bulkrax', ref: '1960bacc48fbb48c5d6f697a9849ddb1a823f867'
gem 'jquery-datatables'

# Dependices for Thumbnail Creation
# =====================================================
gem 'mini_magick'
gem 'open-uri'

# background jobs
# =====================================================
# sidekiq 7 is not compatible with rails 5.2
gem 'sidekiq'
gem "sidekiq-cron"
gem 'sidekiq-failures'
gem 'sidekiq-unique-jobs'

# Hydra Dependencies
# =====================================================
# TEMPORARY: Using wvulibraries fork (Fedora 6 support)
# TODO: Return to samvera/active_fedora main once upstream compatibility verified
# See: ../issues.md - Phase 0 for migration plan
# Fork created to work around deleted fedora6-cjcolvar-rebase branch (was merged to main on Dec 4, 2025)
gem 'active-fedora', git: 'https://github.com/wvulibraries/active_fedora.git', ref: '9b5352009407a6254b9e3db408d2c9554efeaf55'
gem 'active-triples'
gem 'blacklight'
gem 'blacklight_advanced_search'
gem 'blacklight_range_limit'

gem 'hydra-head'
# gem 'ldp'
gem 'nokogiri'
gem 'solrizer'
gem 'speedy-af', '~> 0.3'

gem 'rsolr'
gem 'devise'
gem 'devise-guests', '~> 0.5'

# Questioning Authority
# =====================================================
gem 'qa'

# EDTF-Ruby
# =====================================================
gem 'edtf'

# ISO 639
# =====================================================
gem 'iso-639'

# Capistrano
# =====================================================
# gem 'capistrano-rails'

# DEVELOPMENT AND TESTS ONLY
# =====================================================
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'jettywrapper'
  gem 'listen'
  gem 'fcrepo_wrapper', '~> 0.4'
  gem 'solr_wrapper', '~> 2.0'
end

group :test do
  gem 'factory_bot_rails'
  gem 'webmock'
  gem 'simplecov', require: false
  gem 'simplecov-lcov', require: false
  gem 'rspec_junit_formatter'  
  gem 'rails-controller-testing'
end

group :development do
  gem 'letter_opener_web'
  gem 'web-console', '>= 3.3.0'
  gem 'spring', '< 4.0.0'
end
