source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0.preview2'

# Rails Dependencies
# =====================================================
gem 'rails', '~> 6.1.7.6'
gem 'bundler'
gem 'rake', '~> 13.0.1'
gem 'puma', '~> 6.4.0'
gem 'pg', '>= 0.18', '< 2.0'
# gem 'uglifier', '>= 1.3.0'
gem 'terser', '>= 1.0.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# gem 'sdoc', '~> 0.4.0', group: :doc

# Frontend Dependencies
# =====================================================
gem "sassc-rails", "~> 2.1"
gem "sprockets-rails"
gem "bootstrap", "\~\>\ 5.1"
gem 'bootsnap', '>= 1.4.2', require: false

# OAI-PMH
# =====================================================
gem 'blacklight_oai_provider', github: 'projectblacklight/blacklight_oai_provider', ref: '428da77'

# Blacklight Range Limit for date searches
# =====================================================
gem 'blacklight_range_limit'

# Automatic Import
# =====================================================
gem 'whenever', require: false

# Bulkrax Import
# =====================================================
# Switch the comments on these two lines to work on Bulkrax locally
gem 'bulkrax', git: 'https://github.com/samvera-labs/bulkrax.git', ref: 'b689afa'
# gem 'bulkrax', path: 'vendor/engines/bulkrax'

# Dependices for Thumbnail Creation
# =====================================================
gem 'mini_magick'
gem 'open-uri'

# background jobs
# =====================================================
gem 'sidekiq', '~> 6.1', '>= 6.1.3'
gem "sidekiq-cron"
gem 'sidekiq-failures'

# Hydra Dependencies
# =====================================================
gem 'active-fedora', git: 'https://github.com/samvera/active_fedora.git', branch: 'fedora6-cjcolvar-rebase'
gem 'active-triples'
gem 'blacklight'
gem 'blacklight_advanced_search'

gem 'hydra-head'
# gem 'ldp'
gem 'nokogiri'
gem 'solrizer'

gem 'rsolr', '>= 1.0', '< 3'
gem 'devise'
gem 'devise-guests', '~> 0.5'

# Questioning Authority
# =====================================================
gem 'qa'

# Capistrano
# =====================================================
# gem 'capistrano-rails'

# DEVELOPMENT AND TESTS ONLY
# =====================================================
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec-rails'
  gem 'jettywrapper'
  gem 'listen'
  gem 'fcrepo_wrapper', '~> 0.4'
  gem 'solr_wrapper', '~> 2.0'
end

group :test do
  gem 'factory_bot_rails'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'spring', '< 4.0.0'
end
